# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 329c2b9f5c6d5421c11f4b166f5371256397b4b0f59dbab1ae6938748ba9e1591893b79e18971eb778c75f24147dd1593ba52d89a6de836d37a4987a813d1e0d

test:
  secret_key_base: 372d2e7b99f2158c2462cadd662343a30f1ff75d920eab6be4b8f756da42a8735c5c38d203f74d15db0d54261cf78ca3374f6f131edc7b2d4fade72e1ee849ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
